import Head from "next/head";
import Articles from "../components/Articles";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Articles from API Json</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <Articles />
    </div>
  );
}
